-- phpMyAdmin SQL Dump
-- version 4.4.15.10
-- https://www.phpmyadmin.net
--
-- Хост: localhost
-- Время создания: Апр 13 2021 г., 17:26
-- Версия сервера: 5.7.31
-- Версия PHP: 5.4.16

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `rnc`
--

-- --------------------------------------------------------

--
-- Структура таблицы `link`
--

CREATE TABLE IF NOT EXISTS `link` (
  `id` int(255) NOT NULL,
  `url_doner` varchar(1000) DEFAULT NULL,
  `url` varchar(1000) DEFAULT NULL,
  `anchor` varchar(1000) DEFAULT NULL,
  `url_id` varchar(1000) DEFAULT NULL,
  `url_title` varchar(1000) DEFAULT NULL,
  `url_pr` varchar(1000) DEFAULT NULL,
  `url_doner_base64` varchar(1000) DEFAULT NULL,
  `dop5` varchar(1000) DEFAULT NULL,
  `status` varchar(1000) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=185 DEFAULT CHARSET=utf8mb4;

--
-- Дамп данных таблицы `link`
--

INSERT INTO `link` (`id`, `url_doner`, `url`, `anchor`, `url_id`, `url_title`, `url_pr`, `url_doner_base64`, `dop5`, `status`) VALUES
(2, 'http://suits24.ru/', 'salehard.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Салехарде (Ямало-Ненецкий автономный округ)', '1', 'Юридические услуги в Санкт-Петербурге', '119', 'aHR0cDovL3N1aXRzMjQucnUv', NULL, '1'),
(3, 'http://suits24.ru/about/', 'noyabrsk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Ноябрьске (Ямало-Ненецкий автономный округ)', '2', 'О нас | Почему мы? | Suits24', '119', 'aHR0cDovL3N1aXRzMjQucnUvYWJvdXQv', NULL, '1'),
(4, 'http://suits24.ru/services/', 'novyij-urengoj.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Новом Уренгое (Ямало-Ненецкий автономный округ)', '3', 'Услуги | Suits24', '119', 'aHR0cDovL3N1aXRzMjQucnUvc2VydmljZXMv', NULL, '1'),
(5, 'http://suits24.ru/services/registration_and_liquidation/', 'chelyabinsk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Челябинске (Челябинская область)', '4', 'Регистрация ООО и ИП «под ключ» | Suits24', '119', 'aHR0cDovL3N1aXRzMjQucnUvc2VydmljZXMvcmVnaXN0cmF0aW9uX2FuZF9saXF1aWRhdGlvbi8=', NULL, '1'),
(6, 'http://suits24.ru/services/legal_business/', 'satka.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Сатке (Челябинская область)', '5', 'Юридическое сопровождение бизнеса | Suits24', '106', 'aHR0cDovL3N1aXRzMjQucnUvc2VydmljZXMvbGVnYWxfYnVzaW5lc3Mv', NULL, '1'),
(7, 'http://suits24.ru/services/pepresentation_arbitration/', 'ozersk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Озерске (Челябинская область)', '6', 'Представительство в суде. Арбитраж. | Suits24', '119', 'aHR0cDovL3N1aXRzMjQucnUvc2VydmljZXMvcGVwcmVzZW50YXRpb25fYXJiaXRyYXRpb24v', NULL, '1'),
(8, 'http://suits24.ru/contacts/', 'miass.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Миассе (Челябинская область)', '7', 'Контакты | Suits24', '119', 'aHR0cDovL3N1aXRzMjQucnUvY29udGFjdHMv', NULL, '1'),
(9, 'http://suits24.ru/blog/', 'magnitogorsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Магнитогорске (Челябинская область)', '8', 'Юридический блог | Suits24', '106', 'aHR0cDovL3N1aXRzMjQucnUvYmxvZy8=', NULL, '1'),
(10, 'http://suits24.ru/nalog_s_perevodov_na_kartu/', 'hantyi-mansijsk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Ханты-Мансийске (Ханты-Мансийский автономный округ)', '9', 'Ваша банковская карты, поступления и налоги | Suits24', '78', 'aHR0cDovL3N1aXRzMjQucnUvbmFsb2dfc19wZXJldm9kb3ZfbmFfa2FydHUv', NULL, '1'),
(11, 'http://suits24.ru/category/бизнес/', 'surgut.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Сургуте (Ханты-Мансийский автономный округ)', '10', 'бизнес | Suits24', '79', 'aHR0cDovL3N1aXRzMjQucnUvY2F0ZWdvcnkv0LHQuNC30L3QtdGBLw==', NULL, '1'),
(12, 'http://suits24.ru/plata_za_vypusk_karty/', 'nijnevartovsk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Нижневартовске (Ханты-Мансийский автономный округ)', '11', 'Плата за выпуск карты — не дайте банку себя обхитрить! | Suits24', '77', 'aHR0cDovL3N1aXRzMjQucnUvcGxhdGFfemFfdnlwdXNrX2thcnR5Lw==', NULL, '1'),
(13, 'http://suits24.ru/category/сделки/', 'nefteyugansk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Нефтеюганске (Ханты-Мансийский автономный округ)', '12', 'сделки | Suits24', '82', 'aHR0cDovL3N1aXRzMjQucnUvY2F0ZWdvcnkv0YHQtNC10LvQutC4Lw==', NULL, '1'),
(14, 'http://suits24.ru/ne_chital_i_podpisal/', 'tyumen.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Тюмени (Тюменская область)', '13', 'Не читал и подписал? Теперь плати! | Suits24', '73', 'aHR0cDovL3N1aXRzMjQucnUvbmVfY2hpdGFsX2lfcG9kcGlzYWwv', NULL, '1'),
(15, 'http://suits24.ru/bivshiy_muzh_ne_platit_alimenty/', 'tobolsk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Тобольске (Тюменская область)', '14', 'Бывший муж не платит алименты? | Suits24', '68', 'aHR0cDovL3N1aXRzMjQucnUvYml2c2hpeV9tdXpoX25lX3BsYXRpdF9hbGltZW50eS8=', NULL, '1'),
(16, 'http://suits24.ru/category/дети/', 'ishim.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Ишиме (Тюменская область)', '15', 'дети | Suits24', '72', 'aHR0cDovL3N1aXRzMjQucnUvY2F0ZWdvcnkv0LTQtdGC0Lgv', NULL, '1'),
(17, 'http://suits24.ru/kak_snizit_rashody_na_ku/', 'kurgan.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Кургане (Курганская область)', '16', 'Как снизить расходы на коммунальные услуги? | Suits24', '70', 'aHR0cDovL3N1aXRzMjQucnUva2FrX3NuaXppdF9yYXNob2R5X25hX2t1Lw==', NULL, '1'),
(18, 'http://suits24.ru/category/недвижимость/', 'pervouralsk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Первоуральске (Свердловская область)', '17', 'недвижимость | Suits24', '73', 'aHR0cDovL3N1aXRzMjQucnUvY2F0ZWdvcnkv0L3QtdC00LLQuNC20LjQvNC+0YHRgtGMLw==', NULL, '1'),
(19, 'http://suits24.ru/povishayshiy_koeff_k_zp/', 'nijnij-tagil.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Нижнем Тагиле (Свердловская область)', '18', 'Повышающий коэффициент к зарплате | Suits24', '66', 'aHR0cDovL3N1aXRzMjQucnUvcG92aXNoYXlzaGl5X2tvZWZmX2tfenAv', NULL, '1'),
(20, 'http://suits24.ru/category/ответы-на-вопросы/', 'kamensk-uralskij.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Каменске-Уральском (Свердловская область)', '19', 'Ответы на вопросы | Suits24', '67', 'aHR0cDovL3N1aXRzMjQucnUvY2F0ZWdvcnkv0L7RgtCy0LXRgtGLLdC90LAt0LLQvtC/0YDQvtGB0Ysv', NULL, '1'),
(21, 'http://suits24.ru/privacy-policy/', 'ekaterinburg.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Екатеринбурге (Свердловская область)', '20', 'Политика конфиденциальности | Suits24', '119', 'aHR0cDovL3N1aXRzMjQucnUvcHJpdmFjeS1wb2xpY3kv', NULL, '1'),
(22, 'http://suits24.ru/franchise/', 'stavropol.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Ставрополе (Ставропольский край)', '21', 'Франшиза | Suits24', '43', 'aHR0cDovL3N1aXRzMjQucnUvZnJhbmNoaXNlLw==', NULL, '1'),
(23, 'http://suits24.ru/news/', 'pyatigorsk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Пятигорске (Ставропольский край)', '22', 'Новости и статьи | Suits24', '14', 'aHR0cDovL3N1aXRzMjQucnUvbmV3cy8=', NULL, '1'),
(24, 'http://suits24.ru/author/azercay/', 'nevinnomyissk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Невинномысске (Ставропольский край)', '23', 'azercay | Suits24', '43', 'aHR0cDovL3N1aXRzMjQucnUvYXV0aG9yL2F6ZXJjYXkv', NULL, '1'),
(25, 'http://suits24.ru/lgotnaya_semeynaya_ipoteka_2018/', 'mineralnyie-vodyi.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Минеральных Водах (Ставропольский край)', '24', 'Льготная семейная ипотека с 2018 года | Suits24', '7', 'aHR0cDovL3N1aXRzMjQucnUvbGdvdG5heWFfc2VtZXluYXlhX2lwb3Rla2FfMjAxOC8=', NULL, '1'),
(26, 'http://suits24.ru/ip_mozhet_ne_platit_nalogi/', 'kislovodsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Кисловодске (Ставропольский край)', '25', 'ИП может не платить налоги | Suits24', '16', 'aHR0cDovL3N1aXRzMjQucnUvaXBfbW96aGV0X25lX3BsYXRpdF9uYWxvZ2kv', NULL, '1'),
(27, 'http://suits24.ru/category/налоги/', 'essentuki.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Ессентуках (Ставропольский край)', '26', 'налоги | Suits24', '19', 'aHR0cDovL3N1aXRzMjQucnUvY2F0ZWdvcnkv0L3QsNC70L7Qs9C4Lw==', NULL, '1'),
(28, 'http://suits24.ru/bank_vparil_strahovku/', 'habarovsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Хабаровске (Хабаровский край)', '27', 'Банк «впарил» страховку? | Suits24', '11', 'aHR0cDovL3N1aXRzMjQucnUvYmFua192cGFyaWxfc3RyYWhvdmt1Lw==', NULL, '1'),
(29, 'http://suits24.ru/kreditny_dogovor-ne_prigovor/', 'komsomolsk-na-amure.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Комсомольске-на-Амуре (Хабаровский край)', '28', 'Кредитный договор — не приговор! | Suits24', '12', 'aHR0cDovL3N1aXRzMjQucnUva3JlZGl0bnlfZG9nb3Zvci1uZV9wcmlnb3Zvci8=', NULL, '1'),
(30, 'http://suits24.ru/blog/page/2/', 'ussurijsk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Уссурийске (Приморский край)', '29', 'Юридический блог | Suits24 - Part 2', '2', 'aHR0cDovL3N1aXRzMjQucnUvYmxvZy9wYWdlLzIv', NULL, '1'),
(31, 'http://suits24.ru/blog/page/3/', 'nahodka.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Находке (Приморский край)', '30', 'Юридический блог | Suits24 - Part 3', '2', 'aHR0cDovL3N1aXRzMjQucnUvYmxvZy9wYWdlLzMv', NULL, '1'),
(32, 'http://suits24.ru/raspiska-kak_ne_poteryat_dengi/', 'vladivostok.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Владивостоке (Приморский край)', '31', 'Расписка — как не потерять деньги? | Suits24', '8', 'aHR0cDovL3N1aXRzMjQucnUvcmFzcGlza2Eta2FrX25lX3BvdGVyeWF0X2RlbmdpLw==', NULL, '1'),
(33, 'http://suits24.ru/tag/банк/', 'magadan-i-oblast.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Магадане и область (Магаднская область)', '32', 'банк | Suits24', '5', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9Cx0LDQvdC6Lw==', NULL, '1'),
(34, 'http://suits24.ru/tag/бизнес/', 'tyinda.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Тынде (Амурская область)', '33', 'бизнес | Suits24', '2', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9Cx0LjQt9C90LXRgS8=', NULL, '1'),
(35, 'http://suits24.ru/tag/деньги/', 'blagoveshensk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Благовещенске (Амурская область)', '34', 'деньги | Suits24', '11', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9C00LXQvdGM0LPQuC8=', NULL, '1'),
(36, 'http://suits24.ru/tag/договор/', 'belogorsk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Белогорске (Амурская область)', '35', 'договор | Suits24', '4', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9C00L7Qs9C+0LLQvtGALw==', NULL, '1'),
(37, 'http://suits24.ru/tag/займ/', 'tomsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Томске (Томская область)', '36', 'займ | Suits24', '4', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9C30LDQudC8Lw==', NULL, '1'),
(38, 'http://suits24.ru/tag/ип/', 'omsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Омске (Омская область)', '37', 'ИП | Suits24', '2', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9C40L8v', NULL, '1'),
(39, 'http://suits24.ru/tag/налоги/', 'novosibirsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Новосибирске (Новосибирская область)', '38', 'налоги | Suits24', '3', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9C90LDQu9C+0LPQuC8=', NULL, '1'),
(40, 'http://suits24.ru/tag/ооо/', 'norilsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Норильске (Красноярский край)', '39', 'ООО | Suits24', '3', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9C+0L7Qvi8=', NULL, '1'),
(41, 'http://suits24.ru/tag/полезно/', 'minusinsk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Минусинске (Красноярский край)', '40', 'полезно | Suits24', '4', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9C/0L7Qu9C10LfQvdC+Lw==', NULL, '1'),
(42, 'http://suits24.ru/tag/предприниматели/', 'krasnoyarsk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Красноярске (Красноярский край)', '41', 'предприниматели | Suits24', '3', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9C/0YDQtdC00L/RgNC40L3QuNC80LDRgtC10LvQuC8=', NULL, '1'),
(43, 'http://suits24.ru/kak_poluchit_650000_rub/', 'jeleznogorsk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Железногорске (Красноярский край)', '42', 'Как получить 650 000 руб. от государства? | Suits24', '7', 'aHR0cDovL3N1aXRzMjQucnUva2FrX3BvbHVjaGl0XzY1MDAwMF9ydWIv', NULL, '1'),
(44, 'http://suits24.ru/российский-инвестиционный-форум-2018/', 'achinsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Ачинске (Красноярский край)', '43', 'Российский инвестиционный форум 2018 | Suits24', '6', 'aHR0cDovL3N1aXRzMjQucnUv0YDQvtGB0YHQuNC50YHQutC40Lkt0LjQvdCy0LXRgdGC0LjRhtC40L7QvdC90YvQuS3RhNC+0YDRg9C8LTIwMTgv', NULL, '1'),
(45, 'http://suits24.ru/tag/должник/', 'novokuznetzk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Новокузнецке (Кемеровская область)', '44', 'должник | Suits24', '4', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9C00L7Qu9C20L3QuNC6Lw==', NULL, '1'),
(46, 'http://suits24.ru/tag/ипотека/', 'mejdurechensk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Междуреченске (Кемеровская область)', '45', 'ипотека | Suits24', '4', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9C40L/QvtGC0LXQutCwLw==', NULL, '1'),
(47, 'http://suits24.ru/tag/кредит/', 'kemerovo.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Кемерово (Кемеровская область)', '46', 'кредит | Suits24', '4', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9C60YDQtdC00LjRgi8=', NULL, '1'),
(48, 'http://suits24.ru/tag/что-делать/', 'ust-ilimsk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Усть-Илимске (Иркутская область)', '47', 'что делать? | Suits24', '4', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9GH0YLQvi3QtNC10LvQsNGC0Ywv', NULL, '1'),
(49, 'http://suits24.ru/tag/взносы/', 'bratsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Братске (Иркутская область)', '72', 'взносы | Suits24', '1', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9Cy0LfQvdC+0YHRiy8=', NULL, '1'),
(50, 'http://suits24.ru/tag/малый-бизнес/', 'angarsk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Ангарске (Иркутская область)', '73', 'малый бизнес | Suits24', '1', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9C80LDQu9GL0Lkt0LHQuNC30L3QtdGBLw==', NULL, '1'),
(51, 'http://suits24.ru/tag/псн/', 'irkutsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Иркутске (Иркутская область)', '74', 'ПСН | Suits24', '1', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9C/0YHQvS8=', NULL, '1'),
(52, 'http://suits24.ru/tag/усн/', 'bijsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Бийске (Алтайский край)', '75', 'УСН | Suits24', '1', 'aHR0cDovL3N1aXRzMjQucnUvdGFnL9GD0YHQvS8=', NULL, '1'),
(53, 'http://suits24.ru/services/legal_consultation/', 'barnaul.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Барнауле (Алтайский край)', '101', 'Юридические консультации | Suits24', '13', 'aHR0cDovL3N1aXRzMjQucnUvc2VydmljZXMvbGVnYWxfY29uc3VsdGF0aW9uLw==', NULL, '1'),
(54, 'http://suits24.ru/services/contract_work/', 'shahtyi.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Шахтах (Ростовская область)', '102', 'Составление документов, договорная работа. | Suits24', '13', 'aHR0cDovL3N1aXRzMjQucnUvc2VydmljZXMvY29udHJhY3Rfd29yay8=', NULL, '1'),
(55, 'http://suits24.ru/services/legal_entities_services/', 'taganrog.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Таганроге (Ростовская область)', '103', 'Услуги для юридических лиц. | Suits24', '13', 'aHR0cDovL3N1aXRzMjQucnUvc2VydmljZXMvbGVnYWxfZW50aXRpZXNfc2VydmljZXMv', NULL, '1'),
(56, 'http://suits24.ru/services/individuals_services/', 'novocherkassk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Новочеркасске (Ростовская область)', '104', 'Услуги для физических лиц. | Suits24', '13', 'aHR0cDovL3N1aXRzMjQucnUvc2VydmljZXMvaW5kaXZpZHVhbHNfc2VydmljZXMv', NULL, '1'),
(57, 'http://suits24.ru/price/', 'kamensk-shahtinskij.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Каменске-Шахтинском (Ростовская область)', '105', 'Цены | Suits24', '13', 'aHR0cDovL3N1aXRzMjQucnUvcHJpY2Uv', NULL, '1'),
(58, 'http://suits24.ru/price/legal_services/', 'volgodonsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Волгодонске (Ростовская область)', '106', 'Юридические услуги | Suits24', '13', 'aHR0cDovL3N1aXRzMjQucnUvcHJpY2UvbGVnYWxfc2VydmljZXMv', NULL, '1'),
(59, 'http://suits24.ru/price/accounting_services/', 'rostov-na-donu.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Ростове-на-Дону (Ростовская область)', '107', 'Бухгалтерские услуги | Suits24', '13', 'aHR0cDovL3N1aXRzMjQucnUvcHJpY2UvYWNjb3VudGluZ19zZXJ2aWNlcy8=', NULL, '1'),
(60, 'http://suits24.ru/банк-впарил-страховку/', 'tuapse.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Туапсе (Краснодарский край)', '108', 'Банк «впарил» страховку? | Suits24', '1', 'aHR0cDovL3N1aXRzMjQucnUv0LHQsNC90Lot0LLQv9Cw0YDQuNC7LdGB0YLRgNCw0YXQvtCy0LrRgy8=', NULL, '1'),
(61, 'http://vashadvokat48.ru/', 'sochi.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Сочи (Краснодарский край)', '1', 'Адвокаты и юристы в Липецке', '111', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUv', NULL, '1'),
(62, 'http://vashadvokat48.ru/page/1168567', 'novorossijsk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Новороссийске (Краснодарский край)', '2', 'Наши услуги - Адвокаты и юристы в Липецке', '109', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xMTY4NTY3', NULL, '1'),
(63, 'http://vashadvokat48.ru/articles', 'krasnodar.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Краснодаре (Краснодарский край)', '3', 'Выигранные дела - Адвокаты и юристы в Липецке', '111', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXM=', NULL, '1'),
(64, 'http://vashadvokat48.ru/page/150666', 'ejsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Ейске (Краснодарский край)', '4', 'Юридическая консультация в Липецке', '111', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xNTA2NjY=', NULL, '1'),
(65, 'http://vashadvokat48.ru/contacts', 'armavir.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Армавире (Краснодарский край)', '5', 'Контактная информация - Ваш адвокат', '111', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvY29udGFjdHM=', NULL, '1'),
(66, 'http://vashadvokat48.ru/page/1333111', 'anapa.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Анапе (Краснодарский край)', '6', 'Ваш адвокат - Адвокаты', '79', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xMzMzMTEx', NULL, '1'),
(67, 'http://vashadvokat48.ru/page/1333112', 'kamyishin.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Камышине (Волгоградская область)', '7', 'Ваш адвокат - Отзывы', '79', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xMzMzMTEy', NULL, '1'),
(68, 'http://vashadvokat48.ru/page/63845', 'voljskij.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Волжском (Волгоградская область)', '8', 'Адвокаты и юристы по семейным делам в Липецке', '16', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS82Mzg0NQ==', NULL, '1'),
(69, 'http://vashadvokat48.ru/page/181575', 'volgograd.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Волгограде (Волгоградская область)', '9', 'Адвокаты и юристы по пенсионным делам в Липецке', '13', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xODE1NzU=', NULL, '1'),
(70, 'http://vashadvokat48.ru/page/63846', 'astrahan.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Астрахани (Астраханская область)', '10', 'Адвокаты и юристы по трудовым спорам в Липецке', '12', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS82Mzg0Ng==', NULL, '1'),
(71, 'http://vashadvokat48.ru/page/63843', 'cheboksaryi.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Чебоксарах (Чувашская Республика)', '11', 'Адвокаты и юристы по долевому строительству в Липецке', '14', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS82Mzg0Mw==', NULL, '1'),
(72, 'http://vashadvokat48.ru/page/63834', 'novocheboksarsk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Новочебоксарске (Чувашская Республика)', '12', 'Адвокаты и юристы по наследственным делам в Липецке', '12', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS82MzgzNA==', NULL, '1'),
(73, 'http://vashadvokat48.ru/page/63833', 'dimitrovgrad.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Димитровграде (Ульяновская область)', '13', 'Адвокаты и юристы по жилищным делам в Липецке', '15', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS82MzgzMw==', NULL, '1'),
(74, 'http://vashadvokat48.ru/page/168186', 'ulyanovsk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Ульяновске (Ульяновская область)', '14', 'Адвокат по уголовным делам в Липецке', '15', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xNjgxODY=', NULL, '1'),
(75, 'http://vashadvokat48.ru/page/197385', 'sarapul.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Сарапуле (Удмуртская Республика)', '15', 'Адвокаты и юристы по защите прав потребителей в Липецке', '12', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xOTczODU=', NULL, '1'),
(76, 'http://vashadvokat48.ru/page/69342', 'ijevsk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Ижевске (Удмуртская Республика)', '16', 'Адвокаты и юристы по земельным делам в Липецке', '12', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS82OTM0Mg==', NULL, '1'),
(77, 'http://vashadvokat48.ru/page/63844', 'glazov.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Глазове (Удмуртская Республика)', '17', 'Адвокаты и юристы по недвижимости в Липецке', '12', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS82Mzg0NA==', NULL, '1'),
(78, 'http://vashadvokat48.ru/arbitrazh', 'yengels.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Энгельсе (Саратовская область)', '18', 'Ваш адвокат - Арбитражные споры', '10', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJiaXRyYXpo', NULL, '1'),
(79, 'http://vashadvokat48.ru/vzyskanie-dolgov', 'balakovo.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Балаково (Саратовская область)', '19', 'Ваш адвокат - Взыскание долгов', '10', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvdnp5c2thbmllLWRvbGdvdg==', NULL, '1'),
(80, 'http://vashadvokat48.ru/abonentskoe-obsluzhivanie', 'saratov.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Саратове (Саратовская область)', '20', 'Ваш адвокат - Абонентское обслуживание', '10', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYWJvbmVudHNrb2Utb2JzbHV6aGl2YW5pZQ==', NULL, '1'),
(81, 'http://vashadvokat48.ru/bankrotstvo-jurlic', 'tolyatti.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Тольятти (Самарская область)', '21', 'Ваш адвокат - Банкротство', '10', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYmFua3JvdHN0dm8tanVybGlj', NULL, '1'),
(82, 'http://vashadvokat48.ru/page/1264573', 'syizran.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Сызрани (Самарская область)', '22', 'Возврат страховых взносов ФСС - Адвокаты и юристы в Липецке', '10', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xMjY0NTcz', NULL, '1'),
(83, 'http://vashadvokat48.ru/articles/410783', 'samara.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Самаре (Самарская область)', '23', 'Суд признал квартиру личной собственностью жены', '12', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvNDEwNzgz', NULL, '1'),
(84, 'http://vashadvokat48.ru/articles/tag/семейный+спор', 'jigulevsk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Жигулевске (Самарская область)', '24', 'Выигранные дела - Адвокаты и юристы в Липецке', '35', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9GB0LXQvNC10LnQvdGL0Lkr0YHQv9C+0YA=', NULL, '1'),
(85, 'http://vashadvokat48.ru/articles/408500', 'nijnekamsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Нижнекамске (Республика Татарстан)', '25', 'Суд обязал пенсионный фонд включить в специальный стаж для назначения досрочной пенсии периоды работы с тяжелыми условиями труда', '12', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvNDA4NTAw', NULL, '1'),
(86, 'http://vashadvokat48.ru/articles/tag/пенсионный+спор', 'naberejnyie-chelnyi.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Набережных Челнах (Республика Татарстан)', '26', 'Выигранные дела - Адвокаты и юристы в Липецке', '37', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9C/0LXQvdGB0LjQvtC90L3Ri9C5K9GB0L/QvtGA', NULL, '1'),
(87, 'http://vashadvokat48.ru/articles/408488', 'kazan.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Казани (Республика Татарстан)', '28', 'Суд разрешил спор о границах двух земельных участков в пользу нашего клиента', '12', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvNDA4NDg4', NULL, '1'),
(88, 'http://vashadvokat48.ru/articles/tag/земельный+спор', 'bugulma.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Бугульме (Республика Татарстан)', '29', 'Выигранные дела - Адвокаты и юристы в Липецке', '32', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9C30LXQvNC10LvRjNC90YvQuSvRgdC/0L7RgA==', NULL, '1'),
(89, 'http://vashadvokat48.ru/page/150472', 'almetevsk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Альметьевске (Республика Татарстан)', '30', 'Составление договоров. Адвокаты и юристы в Липецке', '6', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xNTA0NzI=', NULL, '1'),
(90, 'http://vashadvokat48.ru/page/144091', 'ufa.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Уфе (Республика Башкортостан)', '31', 'Адвокаты и юристы по разделу имущества супругов', '2', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xNDQwOTE=', NULL, '1'),
(91, 'http://vashadvokat48.ru/page/144066', 'sterlitamak.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Стерлитамаке (Республика Башкортостан)', '32', 'Услуги адвоката по расторжению брака в Липецке', '2', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xNDQwNjY=', NULL, '1'),
(92, 'http://vashadvokat48.ru/page/144092', 'salavat.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Салавате (Республика Башкортостан)', '33', 'Адвокат по лишению родительских прав в Липецке', '2', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xNDQwOTI=', NULL, '1'),
(93, 'http://vashadvokat48.ru/articles/251111', 'oktyabrskij.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Октябрьском (Республика Башкортостан)', '34', 'Договор дарения квартиры без согласия мужа признан недействительным', '6', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjUxMTEx', NULL, '1'),
(94, 'http://vashadvokat48.ru/articles/251123', 'neftekamsk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Нефтекамске (Республика Башкортостан)', '35', 'Вышестоящий суд отменил решение и оставил ребенка проживать с отцом', '6', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjUxMTIz', NULL, '1'),
(95, 'http://vashadvokat48.ru/articles/409076', 'berezniki.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Березниках (Пермский край)', '36', 'Суд отказал во взыскании алиментов в твердой денежной сумме и за предыдущие три года', '4', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvNDA5MDc2', NULL, '1'),
(96, 'http://vashadvokat48.ru/page/1037145', 'perm.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Перми (Пермский край)', '37', 'Досрочная пенсия через суд - Адвокаты и юристы в Липецке', '2', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xMDM3MTQ1', NULL, '1'),
(97, 'http://vashadvokat48.ru/articles/408532', 'penza.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Пензе (Пензенская область)', '38', 'Решение пенсионного фонда об удержании 20% из пенсии клиента признано незаконным', '4', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvNDA4NTMy', NULL, '1'),
(98, 'http://vashadvokat48.ru/articles/362948', 'orsk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Орске (Оренбуржская область)', '39', 'Суд назначил досрочную пенсию с 55 лет в связи с работой в гражданской авиации', '6', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMzYyOTQ4', NULL, '1'),
(99, 'http://vashadvokat48.ru/articles/242441', 'orenburg.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Оренбурге (Оренбуржская область)', '41', 'Наша практика. Адвокаты в Липецке - Советским районным судом г. Липецка за клиентом признано право собственности на наследство. В удовлетворении встречных исковых требований другого наследника отказано', '4', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyNDQx', NULL, '1'),
(100, 'http://vashadvokat48.ru/articles/242662', 'sarov.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Сарове (Нижегородская область)', '42', 'Наша практика. Адвокаты в Липецке - Левобережным районным судом г. Липецка признано право собственности на квартиру и земельный участок в порядке наследования', '4', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyNjYy', NULL, '1'),
(101, 'http://vashadvokat48.ru/articles/tag/наследство', 'nijnij-novgorod.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Нижнем Новгороде (Нижегородская область)', '43', 'Выигранные дела - Адвокаты и юристы в Липецке', '29', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9C90LDRgdC70LXQtNGB0YLQstC+', NULL, '1'),
(102, 'http://vashadvokat48.ru/articles/267636', 'kstovo.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Кстово (Нижегородская область)', '44', 'Спор о взыскании неустойки с застройщика за нарушение срока передачи квартиры завершился заключением мирового соглашения.', '5', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjY3NjM2', NULL, '1'),
(103, 'http://vashadvokat48.ru/articles/243503', 'dzerjinsk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Дзержинске (Нижегородская область)', '45', 'Выигранные дела - Адвокаты и юристы в Липецке - Октябрьский районный суд взыскал с ООО СУ-10 треста «Липецкстрой» неустойку за нарушение срока передачи нежилого помещения', '4', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQzNTAz', NULL, '1'),
(104, 'http://vashadvokat48.ru/page/922378', 'vyiksa.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Выксе (Нижегородская область)', '46', 'Дела в производстве', '8', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS85MjIzNzg=', NULL, '1'),
(105, 'http://vashadvokat48.ru/page/1014032', 'kirov.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Кирове (Кировская область)', '48', 'Неустойка с застройщика. Что нужно знать', '27', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xMDE0MDMy', NULL, '1'),
(106, 'http://vashadvokat48.ru/articles/rss', 'uhta.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Ухте (Республика Коми)', '49', 'Title не получен или отсутствует', '5', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvcnNz', NULL, '1'),
(107, 'http://vashadvokat48.ru/articles/tags', 'usinsk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Усинске (Республика Коми)', '50', 'Ваш адвокат', '25', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFncw==', NULL, '1'),
(108, 'http://vashadvokat48.ru/articles/tag/долевое+строительство', 'syiktyivkar.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Сыктывкаре (Республика Коми)', '52', 'Выигранные дела - Адвокаты и юристы в Липецке', '27', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9C00L7Qu9C10LLQvtC1K9GB0YLRgNC+0LjRgtC10LvRjNGB0YLQstC+', NULL, '1'),
(109, 'http://vashadvokat48.ru/articles/tag/защита+прав+потребителей', 'vorkuta.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Воркуте (Республика Коми)', '53', 'Выигранные дела - Адвокаты и юристы в Липецке', '22', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9C30LDRidC40YLQsCvQv9GA0LDQsivQv9C+0YLRgNC10LHQuNGC0LXQu9C10Lk=', NULL, '1'),
(110, 'http://vashadvokat48.ru/articles/275368', 'sortavala.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Сортавале (Республика Карелия)', '54', 'Суд обязал собственников жилого дома передать ключи от входной двери нашему клиенту', '4', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjc1MzY4', NULL, '1'),
(111, 'http://vashadvokat48.ru/articles/tag/жилищный+спор', 'petrozavodsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Петрозаводске (Республика Карелия)', '55', 'Выигранные дела - Адвокаты и юристы в Липецке', '23', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9C20LjQu9C40YnQvdGL0Lkr0YHQv9C+0YA=', NULL, '1'),
(112, 'http://vashadvokat48.ru/articles/275401', 'kondopoga.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Кондопоге (Республика Карелия)', '56', 'Бывший собственник квартиры отказался добровольно выписаться из квартиры после ее продажи', '4', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjc1NDAx', NULL, '1'),
(113, 'http://vashadvokat48.ru/articles/page/2', 'velikie-luki.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Великих Луках (Псковская область)', '57', 'Выигранные дела - Адвокаты и юристы в Липецке', '5', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvcGFnZS8y', NULL, '1'),
(114, 'http://vashadvokat48.ru/articles/page/3', 'pskov.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Пскове (Псковская область)', '58', 'Выигранные дела - Адвокаты и юристы в Липецке', '5', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvcGFnZS8z', NULL, '1'),
(115, 'http://vashadvokat48.ru/articles/page/4', 'apatityi.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Апатитах (Мурманская область)', '59', 'Выигранные дела - Адвокаты и юристы в Липецке', '5', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvcGFnZS80', NULL, '1'),
(116, 'http://vashadvokat48.ru/articles/tag/жилищные+споры', 'murmansk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Мурманске (Мурманская область)', '60', 'Выигранные дела - Адвокаты и юристы в Липецке', '35', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9C20LjQu9C40YnQvdGL0LUr0YHQv9C+0YDRiw==', NULL, '1'),
(117, 'http://vashadvokat48.ru/articles/tag/арбитражные+споры', 'kaliningrad.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Калининграде (Калининградская область)', '61', 'Выигранные дела - Адвокаты и юристы в Липецке', '31', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9Cw0YDQsdC40YLRgNCw0LbQvdGL0LUr0YHQv9C+0YDRiw==', NULL, '1'),
(118, 'http://vashadvokat48.ru/articles/tag/взыскание+ущерба+от+залития', 'cherepovetz.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Череповце (Вологдаская область)', '62', 'Выигранные дела - Адвокаты и юристы в Липецке', '27', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9Cy0LfRi9GB0LrQsNC90LjQtSvRg9GJ0LXRgNCx0LAr0L7RgivQt9Cw0LvQuNGC0LjRjw==', NULL, '1'),
(119, 'http://vashadvokat48.ru/articles/tag/страховой+спор', 'vologda.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Вологде (Вологдаская область)', '63', 'Выигранные дела - Адвокаты и юристы в Липецке', '22', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9GB0YLRgNCw0YXQvtCy0L7QuSvRgdC/0L7RgA==', NULL, '1'),
(120, 'http://vashadvokat48.ru/articles/tag/взыскание+ущерба+от+ДТП', 'velikij-novgorod.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Великом Новгороде (Новгородская область)', '64', 'Выигранные дела - Адвокаты и юристы в Липецке', '26', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9Cy0LfRi9GB0LrQsNC90LjQtSvRg9GJ0LXRgNCx0LAr0L7RgivQlNCi0J8=', NULL, '1'),
(121, 'http://vashadvokat48.ru/articles/tag/недвижимость', 'severodvinsk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Северодвинске (Архангельскская область)', '65', 'Выигранные дела - Адвокаты и юристы в Липецке', '26', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9C90LXQtNCy0LjQttC40LzQvtGB0YLRjA==', NULL, '1'),
(122, 'http://vashadvokat48.ru/articles/tag/кредитные+споры', 'arhangelsk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Архангельске (Архангельскская область)', '66', 'Выигранные дела - Адвокаты и юристы в Липецке', '26', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9C60YDQtdC00LjRgtC90YvQtSvRgdC/0L7RgNGL', NULL, '1'),
(123, 'http://vashadvokat48.ru/articles/tag/компенсация+морального+вреда', 'tihvin.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Тихвине (Санкт-Петербург и Ленинградская область)', '67', 'Выигранные дела - Адвокаты и юристы в Липецке', '26', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9C60L7QvNC/0LXQvdGB0LDRhtC40Y8r0LzQvtGA0LDQu9GM0L3QvtCz0L4r0LLRgNC10LTQsA==', NULL, '1'),
(124, 'http://vashadvokat48.ru/articles/tag/арбитражный+спор', 'sosnovyij-bor.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Сосновом Боре (Санкт-Петербург и Ленинградская область)', '68', 'Выигранные дела - Адвокаты и юристы в Липецке', '22', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9Cw0YDQsdC40YLRgNCw0LbQvdGL0Lkr0YHQv9C+0YA=', NULL, '1'),
(125, 'http://vashadvokat48.ru/articles/tag/взыскание+денежных+средств', 'kirishi.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Киришах (Санкт-Петербург и Ленинградская область)', '69', 'Выигранные дела - Адвокаты и юристы в Липецке', '26', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9Cy0LfRi9GB0LrQsNC90LjQtSvQtNC10L3QtdC20L3Ri9GFK9GB0YDQtdC00YHRgtCy', NULL, '1'),
(126, 'http://vashadvokat48.ru/page/63842', 'gatchina.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Гатчине (Санкт-Петербург и Ленинградская область)', '70', 'Адвокат по уголовным делам в Липецке', '2', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS82Mzg0Mg==', NULL, '1'),
(127, 'http://vashadvokat48.ru/page/896335', 'vyiborg.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Выборге (Санкт-Петербург и Ленинградская область)', '71', 'Адвокат по делам частного обвинения в Липецке', '2', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS84OTYzMzU=', NULL, '1'),
(128, 'http://vashadvokat48.ru/page/164224', 'vsevolojsk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Всеволожске (Санкт-Петербург и Ленинградская область)', '72', 'Адвокат по УДО в Липецке', '2', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xNjQyMjQ=', NULL, '1'),
(129, 'http://vashadvokat48.ru/page/168185', 'volhov.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Волхове (Санкт-Петербург и Ленинградская область)', '73', 'Представительство потерпевших по уголовному делу', '2', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xNjgxODU=', NULL, '1'),
(130, 'http://vashadvokat48.ru/page/153751', 'sankt-peterburg.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Санкт-Петербурге (Санкт-Петербург и Ленинградская область)', '74', 'Узаконивание перепланировки. Услуги юристов в Липецке', '2', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xNTM3NTE=', NULL, '1'),
(131, 'http://vashadvokat48.ru/page/136384', 'tutaev.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Тутаеве (Ярославская область)', '75', 'Взыскание ущерба от залития квартиры в Липецке', '2', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xMzYzODQ=', NULL, '1'),
(132, 'http://vashadvokat48.ru/page/212254', 'ryibinsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Рыбинске (Ярославская область)', '76', 'Составление договора купли-продажи недвижимости в Липецке', '2', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8yMTIyNTQ=', NULL, '1'),
(133, 'http://vashadvokat48.ru/sem-books', 'yaroslavl.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Ярославле (Ярославская область)', '77', 'Книги по семейным спорам', '2', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvc2VtLWJvb2tz', NULL, '1'),
(134, 'http://vashadvokat48.ru/page/1264401', 'novomoskovsk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Новомосковске (Тульская область)', '78', 'Составление правовых документов в Липецке', '2', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xMjY0NDAx', NULL, '1'),
(135, 'http://vashadvokat48.ru/articles/242649', 'tula.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Туле (Тульская область)', '79', 'Наша практика. Адвокаты в Липецке - Октябрьским районным судом г. Липецкая признано право собственности на долю в жилом доме в порядке наследования по завещанию', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyNjQ5', NULL, '1'),
(136, 'http://vashadvokat48.ru/articles/244970', 'tver.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Твери (Тверская область)', '82', 'Судом вынесено решение о снятии дочери клиента с регистрационного учета', '4', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQ0OTcw', NULL, '1'),
(137, 'http://vashadvokat48.ru/articles/243742', 'tambov.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Тамбове (Тамбовская область)', '83', 'Суд определил порядок оплаты коммунальных услуг между проживающими', '4', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQzNzQy', NULL, '1'),
(138, 'http://vashadvokat48.ru/articles/275460', 'smolensk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Смоленске (Смоленская область)', '84', 'С банка была взыскана сумма страхового возмещения, которую страховая компания перечислила на счет умершего супруга.', '5', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjc1NDYw', NULL, '1'),
(139, 'http://vashadvokat48.ru/articles/242378', 'ryazan.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Рязани (Рязанская область)', '85', 'Арбитражный суд взыскал задолженность по договору поставки', '4', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyMzc4', NULL, '1'),
(140, 'http://vashadvokat48.ru/articles/242392', 'orel.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Орле (Орловская область)', '86', 'Суд взыскал с управляющей компании ущерб, причиненный залитием', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyMzky', NULL, '1'),
(141, 'http://vashadvokat48.ru/articles/242393', 'lipetzk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Липецке (Липецкая область)', '87', 'Наша практика. Адвокаты в Липецке - Арбитражным судом Липецкой области с ОАО "Липецкавтомост" взыскана задолженность по договору оказания услуг в размере 10000 руб.', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyMzkz', NULL, '1'),
(142, 'http://vashadvokat48.ru/articles/242404', 'kursk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Курске (Курская область)', '88', 'Наша практика. Адвокаты в Липецке - Арбитражным судом Липецкой области с ОАО "Завод Железобетон" взыскана задолженность по договору оказания услуг в размере 240000 руб.', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyNDA0', NULL, '1'),
(143, 'http://vashadvokat48.ru/articles/242409', 'kostroma.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Костроме (Костромская область)', '89', 'Наша практика. Адвокаты в Липецке - Левобережным районным судом г. Липецка с управляющей компании взыскан ущерб, причиненный залитием, в размере 77200 руб., штраф, а также компенсация морального вреда', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyNDA5', NULL, '1'),
(144, 'http://vashadvokat48.ru/articles/page/1', 'kaluga.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Калуге (Калужская область)', '90', 'Наша практика. Адвокаты в Липецке', '4', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvcGFnZS8x', NULL, '1'),
(145, 'http://vashadvokat48.ru/articles/242413', 'ivanovo.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Иваново (Ивановоская область)', '91', 'Наша практика. Адвокаты в Липецке - Левобережным районным судом г. Липецка с организации, ведущей дорожные работы, взыскан ущерб, причиненный автомобилю в результате наезда на строительный мусор', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyNDEz', NULL, '1'),
(146, 'http://vashadvokat48.ru/articles/243504', 'voronej.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Воронеже (Воронежская область)', '92', 'Наша практика. Адвокаты в Липецке - Советский районный суд г. Липецка признал садовый домик пригодным для постоянного проживания', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQzNTA0', NULL, '1'),
(147, 'http://vashadvokat48.ru/articles/242423', 'murom.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Муроме (Владимирская область)', '93', 'Наша практика. Адвокаты в Липецке - Октябрьским районным судом г. Липецка с ООО "Бутырский источник" в пользу клиента взысканы денежные средства, уплаченные по предварительному договору купли-продажи, а также незаконно удержанный штраф в размере 40000 руб', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyNDIz', NULL, '1'),
(148, 'http://vashadvokat48.ru/articles/242436', 'kovrov.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Коврове (Владимирская область)', '94', 'Наша практика. Адвокаты в Липецке - Судом апелляционной инстанции отменено решение суда первой инстанции о взыскании с клиента задолженности по кредиту в размере 91678 руб. Банку "ТРАСТ" полностью отказано в удовлетворении исковых требований', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyNDM2', NULL, '1'),
(149, 'http://vashadvokat48.ru/articles/242648', 'vladimir.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Владимире (Владимирская область)', '95', 'Арбитражным судом Липецкой области с ООО "С" взыскана задолженность по договору оказания охранных услуг в размере 52450 руб.', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyNjQ4', NULL, '1'),
(150, 'http://vashadvokat48.ru/articles/243278', 'bryansk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Брянске (Брянская область)', '96', 'Наша практика. Адвокаты в Липецке - Ответчик в ходе рассмотрения дела Лебедянским районным судом добровольно возместил моральный вред, причиненный ДТП', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQzMjc4', NULL, '1'),
(151, 'http://vashadvokat48.ru/articles/242710', 'staryij-oskol.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Старом Осколе (Белгородская область)', '97', 'Наша практика. Адвокаты в Липецке - Арбитражным судом Липецкой области штраф, наложенный УПФР в г. Липецке на клиента, в размере 29444,8 руб. признан незаконным и снижен до 3000 руб.', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyNzEw', NULL, '1'),
(152, 'http://vashadvokat48.ru/articles/242726', 'belgorod.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Белгороде (Белгородская область)', '98', 'Наша практика. Адвокаты в Липецке - Арбитражным судом Липецкой области с ООО "Механические Бизнес Системы" взыскана неустойка по договору поставки обородувания в размере 282290 руб.', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyNzI2', NULL, '1'),
(153, 'http://vashadvokat48.ru/articles/242706', 'yubilejnyij.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Юбилейном (Москва и Московская область)', '99', 'Выигранные дела - Адвокаты и юристы в Липецке - Советским районным судом г. Липецка ответчик снят с регистрационного учета в квартире, которая принадлежит клиенту на праве собственности', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyNzA2', NULL, '1'),
(154, 'http://vashadvokat48.ru/articles/243274', 'shelkovo.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Щелково (Москва и Московская область)', '100', 'Выигранные дела - Адвокаты и юристы в Липецке - Решением Октябрьского районного суда г. Липецка ответчики признаны неприобретшими право пользования квартирой', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQzMjc0', NULL, '1'),
(155, 'http://vashadvokat48.ru/articles/242711', 'chernogolovka.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Черноголовке (Москва и Московская область)', '101', 'Выигранные дела - Адвокаты и юристы в Липецке - Правобережным районным судом г. Липецка признано право клиента на получение жилищного сертификата как вынужденного переселенца', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyNzEx', NULL, '1'),
(156, 'http://vashadvokat48.ru/articles/242727', 'fryazino.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Фрязино (Москва и Московская область)', '102', 'Выигранные дела - Адвокаты и юристы в Липецке - Советским районным судом г. Липецка клиенту разрешено сохранить квартиру в перепланированном состоянии', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyNzI3', NULL, '1'),
(157, 'http://vashadvokat48.ru/articles/242814', 'serpuhov.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Серпухове (Москва и Московская область)', '103', 'Выигранные дела - Адвокаты и юристы в Липецке - Решением Октябрьского рйонного суда г. Липецка истцу разрешено сохранить квартиру в перепланированном состоянии', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQyODE0', NULL, '1'),
(158, 'http://vashadvokat48.ru/articles/243224', 'sergiev-posad.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Сергиевом Посаде (Москва и Московская область)', '104', 'Выигранные дела - Адвокаты и юристы в Липецке - Октябрьский районный суд г. Липецка принял решение о снятии бывшего супруга с регистрационного учета', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvMjQzMjI0', NULL, '1'),
(159, 'http://vashadvokat48.ru/allbooks', 'ramenskoe.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Раменском (Москва и Московская область)', '105', 'Наши книги', '4', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYWxsYm9va3M=', NULL, '1'),
(160, 'http://vashadvokat48.ru/page/75849', 'pushino.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Пущино (Москва и Московская область)', '106', 'Услуги юридическим лицам. Адвокаты и юристы', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS83NTg0OQ==', NULL, '1'),
(161, 'http://vashadvokat48.ru/page/182268', 'podolsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Подольске (Москва и Московская область)', '107', 'Услуги адвокатов и юристов по взысканию долгов в Липецке', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS8xODIyNjg=', NULL, '1'),
(162, 'http://vashadvokat48.ru/page/954111', 'orehovo-zuevo.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Орехово-Зуево (Москва и Московская область)', '108', 'Банкротство физических лиц. Адвокаты и юристы в Липецке', '2', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvcGFnZS85NTQxMTE=', NULL, '1'),
(163, 'http://vashadvokat48.ru/contacts/showmap/193084/0/ru_RU', 'mojajsk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Можайске (Москва и Московская область)', '109', '', '2', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvY29udGFjdHMvc2hvd21hcC8xOTMwODQvMC9ydV9SVQ==', NULL, '1'),
(164, 'http://vashadvokat48.ru/articles/tag/страховые+споры', 'krasnogorsk.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Красногорске (Москва и Московская область)', '110', 'Наша практика. Адвокаты в Липецке', '4', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9GB0YLRgNCw0YXQvtCy0YvQtSvRgdC/0L7RgNGL', NULL, '1'),
(165, 'http://vashadvokat48.ru/articles/tag/семейные+споры', 'korolev.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Королёве (Москва и Московская область)', '111', 'Наша практика. Адвокаты в Липецке', '3', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvYXJ0aWNsZXMvdGFnL9GB0LXQvNC10LnQvdGL0LUr0YHQv9C+0YDRiw==', NULL, '1'),
(166, 'http://vashadvokat48.ru/isk-book-read', 'kolomna.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Коломне (Москва и Московская область)', '113', 'Читать книгу "Семь ошибок при составлении иска"', '2', 'aHR0cDovL3Zhc2hhZHZva2F0NDgucnUvaXNrLWJvb2stcmVhZA==', NULL, '1'),
(167, 'http://mikhailov-partners.ru/', 'klimovsk.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Климовске (Москва и Московская область)', '1', 'Ð®ÑÐ¸Ð´Ð¸ÑÐµÑÐºÐ°Ñ ÐºÐ¾Ð¼Ð¿Ð°Ð½Ð¸Ñ | ÐÐ¸ÑÐ°Ð¹Ð»Ð¾Ð², ÐÐ¾Ð»Ð¼Ð°ÑÐ¾Ð²Ð° Ð¸ ÐÐ°ÑÑÐ½ÐµÑÑ', '1', 'aHR0cDovL21pa2hhaWxvdi1wYXJ0bmVycy5ydS8=', NULL, '1');
INSERT INTO `link` (`id`, `url_doner`, `url`, `anchor`, `url_id`, `url_title`, `url_pr`, `url_doner_base64`, `dop5`, `status`) VALUES
(168, 'http://pl-law.ru/', 'ivanteevka.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Ивантеевке (Москва и Московская область)', '1', 'Юридическая компания "Право Людям" | СПб', '34', 'aHR0cDovL3BsLWxhdy5ydS8=', NULL, '1'),
(169, 'http://pl-law.ru/для-физических-лиц/', 'jukovskij.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Жуковском (Москва и Московская область)', '3', 'Для физических лиц | Юридическая компания "Право Людям"| Спб', '34', 'aHR0cDovL3BsLWxhdy5ydS/QtNC70Y8t0YTQuNC30LjRh9C10YHQutC40YUt0LvQuNGGLw==', NULL, '1'),
(170, 'http://pl-law.ru/для-юридических-лиц/', 'jeleznodorojnyij.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Железнодорожном (Москва и Московская область)', '4', 'Для юридических лиц | Юридическая компания "Право Людям"| Спб', '34', 'aHR0cDovL3BsLWxhdy5ydS/QtNC70Y8t0Y7RgNC40LTQuNGH0LXRgdC60LjRhS3Qu9C40YYv', NULL, '1'),
(171, 'http://pl-law.ru/стоимость-услуг/', 'dubna.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Дубне (Москва и Московская область)', '5', 'Стоимость услуг | Юридическая компания "Право Людям"| Спб', '34', 'aHR0cDovL3BsLWxhdy5ydS/RgdGC0L7QuNC80L7RgdGC0Ywt0YPRgdC70YPQsy8=', NULL, '1'),
(172, 'http://pl-law.ru/контакты/', 'dolgoprudnyij.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Долгопрудном (Москва и Московская область)', '6', 'Контакты | Юридическая компания "Право Людям"| Спб', '34', 'aHR0cDovL3BsLWxhdy5ydS/QutC+0L3RgtCw0LrRgtGLLw==', NULL, '1'),
(173, 'http://pl-law.ru/прайс-лист-на-юридические-услуги/', 'dmitrov.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Дмитрове (Москва и Московская область)', '8', 'Прайс-лист на юридические услуги | Юридическая компания "Право Людям"| Спб', '19', 'aHR0cDovL3BsLWxhdy5ydS/Qv9GA0LDQudGBLdC70LjRgdGCLdC90LAt0Y7RgNC40LTQuNGH0LXRgdC60LjQtS3Rg9GB0LvRg9Cz0Lgv', NULL, '1'),
(174, 'http://pl-law.ru/прайс-лист-на-абонентское-обслуживан/', 'voskresensk.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в Воскресенске (Москва и Московская область)', '9', 'Прайс-лист на абонентское обслуживание юридических лиц | Юридическая компания "Право Людям"| Спб', '2', 'aHR0cDovL3BsLWxhdy5ydS/Qv9GA0LDQudGBLdC70LjRgdGCLdC90LAt0LDQsdC+0L3QtdC90YLRgdC60L7QtS3QvtCx0YHQu9GD0LbQuNCy0LDQvS8=', NULL, '1'),
(175, 'http://pl-law.ru/для-физических-лиц/гражданское-право/', 'balashiha.consultant-nalog.ru/audit/mandatory/', 'бязательный аудит в Балашихе (Москва и Московская область)', '10', 'Гражданское право | Юридические услуги от компании "Пасюков и Лёхов"| Спб', '1', 'aHR0cDovL3BsLWxhdy5ydS/QtNC70Y8t0YTQuNC30LjRh9C10YHQutC40YUt0LvQuNGGL9Cz0YDQsNC20LTQsNC90YHQutC+0LUt0L/RgNCw0LLQvi8=', NULL, '1'),
(176, 'http://pl-law.ru/для-физических-лиц/жилищное-право/', 'moskva.consultant-nalog.ru/audit/mandatory/', 'Отчет аудитора в Москве (Москва и Московская область)', '11', 'Жилищное право | Юридические услуги от компании "Пасюков и Лёхов"| Спб', '1', 'aHR0cDovL3BsLWxhdy5ydS/QtNC70Y8t0YTQuNC30LjRh9C10YHQutC40YUt0LvQuNGGL9C20LjQu9C40YnQvdC+0LUt0L/RgNCw0LLQvi8=', NULL, '1'),
(177, 'http://pl-law.ru/для-физических-лиц/земельное-право/', '.consultant-nalog.ru/audit/mandatory/', 'Аудиторское заключение в  ()', '12', 'Земельное право | Юридические услуги от компании "Пасюков и Лёхов"| Спб', '1', 'aHR0cDovL3BsLWxhdy5ydS/QtNC70Y8t0YTQuNC30LjRh9C10YHQutC40YUt0LvQuNGGL9C30LXQvNC10LvRjNC90L7QtS3Qv9GA0LDQstC+Lw==', NULL, '1'),
(178, 'http://pl-law.ru/для-физических-лиц/семейное-право/', NULL, NULL, '13', 'Семейное право | Юридические услуги от группы компаний "ПроЛидерКонсалт"| Спб', '1', 'aHR0cDovL3BsLWxhdy5ydS/QtNC70Y8t0YTQuNC30LjRh9C10YHQutC40YUt0LvQuNGGL9GB0LXQvNC10LnQvdC+0LUt0L/RgNCw0LLQvi8=', NULL, NULL),
(179, 'http://pl-law.ru/для-физических-лиц/трудовое-право/', NULL, NULL, '14', 'Трудовое право | Юридические услуги от компании "Пасюков и Лёхов"| Спб', '1', 'aHR0cDovL3BsLWxhdy5ydS/QtNC70Y8t0YTQuNC30LjRh9C10YHQutC40YUt0LvQuNGGL9GC0YDRg9C00L7QstC+0LUt0L/RgNCw0LLQvi8=', NULL, NULL),
(180, 'http://pl-law.ru/для-физических-лиц/уголовное-право/', NULL, NULL, '15', 'Уголовное право | Юридические услуги от компании "Пасюков и Лёхов"| Спб', '1', 'aHR0cDovL3BsLWxhdy5ydS/QtNC70Y8t0YTQuNC30LjRh9C10YHQutC40YUt0LvQuNGGL9GD0LPQvtC70L7QstC90L7QtS3Qv9GA0LDQstC+Lw==', NULL, NULL),
(181, 'http://pl-law.ru/главная/онлайн-запись-на-юридическую-консуль/', NULL, NULL, '16', 'Онлайн запись на юридическую консультацию | Юридическая компания "Право Людям"| Спб', '9', 'aHR0cDovL3BsLWxhdy5ydS/Qs9C70LDQstC90LDRjy/QvtC90LvQsNC50L0t0LfQsNC/0LjRgdGMLdC90LAt0Y7RgNC40LTQuNGH0LXRgdC60YPRji3QutC+0L3RgdGD0LvRjC8=', NULL, NULL),
(182, 'http://pl-law.ru/взыскание-неустойки-с-застройщика/', NULL, NULL, '24', 'Взыскание неустойки с Застройщика | Юридическая компания "Право Людям"| Спб', '2', 'aHR0cDovL3BsLWxhdy5ydS/QstC30YvRgdC60LDQvdC40LUt0L3QtdGD0YHRgtC+0LnQutC4LdGBLdC30LDRgdGC0YDQvtC50YnQuNC60LAv', NULL, NULL),
(183, 'http://pl-law.ru/возврат-навязанной-страховки/', NULL, NULL, '25', 'Возврат навязанной страховки | Юридическая компания "Право Людям"| Спб', '1', 'aHR0cDovL3BsLWxhdy5ydS/QstC+0LfQstGA0LDRgi3QvdCw0LLRj9C30LDQvdC90L7QuS3RgdGC0YDQsNGF0L7QstC60Lgv', NULL, NULL),
(184, 'http://pl-law.ru/для-физических-лиц/земельное-право/изменение-вида-разрешенного-использ/', NULL, NULL, '29', 'Изменение вида разрешенного использования земельных участков | Юридические услуги от компании "ПроЛидерКонсалт"| Спб', '1', 'aHR0cDovL3BsLWxhdy5ydS/QtNC70Y8t0YTQuNC30LjRh9C10YHQutC40YUt0LvQuNGGL9C30LXQvNC10LvRjNC90L7QtS3Qv9GA0LDQstC+L9C40LfQvNC10L3QtdC90LjQtS3QstC40LTQsC3RgNCw0LfRgNC10YjQtdC90L3QvtCz0L4t0LjRgdC/0L7Qu9GM0Lcv', NULL, NULL);

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `link`
--
ALTER TABLE `link`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `link`
--
ALTER TABLE `link`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=185;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
